# Measurement in the Social Sciences

One of the primary motivations for building the GEAM Core tool is to facilitate the generation of high quality data regarding gender equality issues within a given organization or organizational unit. Although such tools as Survey Monkey or Google Forms make it relatively easy to launch surveys and gather data, designing a survey that actually measures certain phenomena in a **valid** and **reliable** way is more difficult [@BrymanSocialresearchmethods2008]. 

**Validity** indicates that a given indicator actually measures the concept it is supposed to measure. For example, questions and answer options that should measure work-life balance could target only working time-arrangements or be more specific and inquire about the degree with which work interferes with private life and vice versa. Validity implies a **theoretical argument** regarding how a certain social phenomena is conceived and manifest. Problematic are indicators that are supposed to measure social phenomena which rely upon a very fuzzy definition of the construct itself. What is meant by “job satisfaction” or “living standard” is not straight forward to answer. For the GEAM we have reviewed available measurement scales and their underlying constructs in @AldercotteACTGenderEquality2019.

**Reliability** refers to the overall consistency of a measure. A given measure is said to be reliable if it produces **similar results over time**, on different occasions, or different people performing the measurement. Reliability of measurement is important especially for documenting change over time; only if an instrument is reliable can you be sure that detected changes are due to a changing social reality and not a “mal-functioning” measurement instrument. 

Reliability does not imply validity. A reliable measure which produces consistent results under varying conditions does not imply that it measures the phenomena of interest. 


## Data types 
The survey collects four types of data. Understanding the type of data collected will assist with subsequent analysis and deciding which statistical tests to run.

### Categorical/nominal data
Is information that is grouped into categories such as gender, locations, research fields, religions, yes, no responses.  This measurement does not order data into any ordered rank or hierarchy even though it can be coded, during data handling, into numbers. For example: 1 (Woman), 2 (Man), 3 (Non-binary), 4 (Other). The numbers assigned to categorical data hold no value or meaning. This data can be counted.

### Rank order/ordinal data
Is categorical information that is placed into an arbitrary rank order or hierarchy such as scale responses in surveys: poor, fair, good or 1 (no formal education), 2 (primary education), 3 (secondary education) and so on. Responses options are given value according to the scale created so they can be counted and compared.

### Discrete/interval data
Is arbitrary measurements at set intervals such as number of incidents/ occurrence of an event, grouped ranges of measurements and scale responses: strongly disagree (1), disagree (2), neutral (3) agree (4) strongly agree (5) or €25,000 and under, €25,001 - €50,000, and over €50,001. 

### Continuous/ratio data
Is numbered data such as age, weight, height depth, width, (ungrouped) salary, counts of something or someone. The measurements in this data type are based on a ‘true’ zero and can be taken at face value as accurate dimensions.


